//Base de datos de coros e himnos
var listaCorosA = [
    ["1.5.1","  ESCUCHA SEÑOR MI ORACION","Escucha Señor mi oración,","considera mis pensamientos,","atiende a la voz de mi clamor,","mi Rey y mi Dios.","Porque a Tí oraré,","oirás mi voz de mañana,","Oh Dios, de mañana me presentaré,","ante Tí esperaré.","",""],
    ["1.5.2","  OH JEHOVÁ, DE MAÑANA OIRÁS MI VOZ (Salmo 5:3)","Oh Jehová, de mañana oirás mi voz,","de mañana me presentaré,","delante de ti esperaré.","Oh Jehová, por la tarde oirás mi voz,","por la tarde me presentaré,","delante de ti esperaré.","Oh Jehová, por la noche oirás mi voz,","por la noche me presentaré,","delante de ti esperaré.","",""],
    ["1.9.1","  TE ALABARE, JEHOVÁ  (Salmo 9)","Te alabaré, Jehová,","//con todo mi corazón,//","// te alabaré, Jehová.//","Cantaré","//todas tus maravillas,//","// te alabaré, Jehová.//","Me alegraré en ti,","//y me regocijaré,//","// te alabaré, Jehová.//","Cantaré a tu nombre,","//oh altísimo,//","// te alabaré, Jehová.//","",""],
    ["1.9.2","  A DIOS ALABARE (Sal. 9.1, 7-9) ","1. A Dios alabaré, de todo corazón,","y proclamaré sus maravillas,","su Nombre cantaré.","Señor te alabaré, de todo corazón.","Tu eres el Señor, el gozo para mí,","Aleluya.","2. Dios, el Señor es Rey, El permanecerá,","y juzgará al mundo con verdad,","justicia sentará.","Dios el Señor es Rey, su reino es eternal","Los pueblos verán justicia y rectitud,","Aleluya.","3. Al pobre cuidará, y le protegerá,","refugio es Él en tiempo de aflicción.","Su nombre es Salvador.","Al oprimido ve, y le defenderá.","Él salvará, el santo Dios es Él,","Aleluya.","4. Gloria al Padre Dios, loor a Cristo el Rey,","al Santo Espíritu la bendición,","su Nombre alabaré;","Gloria al Creador, loor al Salvador,","al Santo Espíritu Consolador,","a Dios alabo hoy.","",""],
    ["1.16.1","  GUÁRDAME OH DIOS  (Salmo  16:1)","//Guárdame, oh Dios ","porque en ti he confiado,","Oh alma mía","dijiste a Jehová.//","//Tú eres mi Señor,","Tú eres mi Señor,","No hay para mi,","bien fuera de Ti.//","",""],
    ["1.16.2","  EN TU PRESENCIA  (Salmo 16:11)","En tu presencia","hay plenitud de gozo;","delicias a tu diestra","para siempre.","Me mostrarás la senda","de la vida;","en tu presencia","hay plenitud de gozo.","",""],
    ["1.18.1","  DIOS ES EL QUE ME CIÑE DE PODER  (Salmo  18: 23-33)","Dios es que me ciñe de poder,","Quien hace perfecto mi camino;","Quien hace mis pies como de ciervas,","Que me hace estar firme sobre mis alturas.","",""],
    ["1.19.1","  QUE LOS DICHOS DE MI BOCA (Salmo 19:14)","//Que los dichos de mi boca","y la meditación de mi corazón","sean gratos delante de ti, Oh Señor.//","Oh Señor, Oh Señor,","Roca mía, mi Redentor.","Que los dichos de mi boca","y la meditación de mi corazón","sean gratos delante de ti, Oh Señor.","",""],
    ["2.109","  ERES TÚ","Eres Tu, la única razón","de mi adoración, oh Jesús.","Eres Tu, la esperanza que","anhelé tener, oh Jesús.","Confié en ti, me has ayudado,","tu salvación me has regalado.","Hoy hay gozo en mi corazón,","con mi canto te alabaré.","//Te alabaré,  te glorificaré,","te alabaré, mi buen Jesús//","...En todo tiempo te alabaré,","...En todo tiempo te adoraré.","",""],
    ["2.118","  CON MIS MANOS LEVANTADAS","//Con mis manos levantadas hacia el cielo,","me presento ante ti hoy mi Señor,","para recibir de ti la fuerza y el poder,","para vivir junto a ti.//","//Llenas hoy mi corazón con tu presencia,","llenas de alegría y paz todo mi ser.","En cualquier necesidad tu me responderás,","porque me amas, me amas.// ","",""],
    ["3.1"," PUEBLO DE DIOS","1. Pueblo de Dios,","pueblo elegido, y consagrado para cantar,","las maravillas del Señor.","CORO","Y celebremos su gran amor","A-le-lu-ya aleluya.","2. Es el Señor quien nos anuncia","su palabra, es el Señor quien","nos invita a la oración.","CORO","Y celebremos su gran amor","A-le-lu-ya aleluya.","3. Es el Señor quien alimenta","nuestra vida, es el Señor quien","se nos da la comunión.","CORO","Y celebremos su gran amor","A-le-lu-ya aleluya.","",""],
    ["5.34"," CRISTO TE NECESITA PARA AMAR","//1. Cristo te necesita para amar, para amar,","Cristo te necesita para amar.//","CORO:","//No te importe la raza ni el color de la piel,","ama a todos como hermanos y haz el bien.//","2. Al que sufre y al triste dale amor, dale amor,","al humilde y al pobre dale amor.","Al que viene de lejos dale amor, dale amor,","al que vive a tu lado dale amor.","CORO:","//No te importe la raza ni el color de la piel,","ama a todos como hermanos y haz el bien.//","3. Al que habla otra lengua dale amor, dale amor,","al que piensa distinto dale amor.","Al amigo de siempre dale amor, dale amor,","al que no te salude dale amor.","CORO:","//No te importe la raza ni el color de la piel,","ama a todos como hermanos y haz el bien.//","",""],
    ["6.39","  AHORA MISMO SEÑOR (JESUS ESTA PASANDO POR AQUI)","//Ahora mismo Señor,//","yo te pido que rompas las cadenas.//","//Que se abran las puertas de los cielos,","y de virtud mi alma sea llena.//","//Jesús está pasando por aquí.//","Y cuando El pasa todo se transforma,","se va la tristeza, llega la alegría.","Y cuando El pasa todo se transforma,","llega la alegría para ti y para mi.","",""],
    ["6.64","  VEN ESPIRITU VEN","//Ven, Espíritu ven,","y lléname Señor","con Tu preciosa unción.//","Purifícame y lávame,","renuévame, restáurame Señor,","con Tu poder.","Purifícame y lávame,","renuévame, restáurame Señor,","te quiero conocer.","",""],
    ["H.269","   Sembraré la simiente preciosa","1. Sembraré la simiente preciosa,","del glorioso evangelio de amor.","Sembraré, sembraré mientras viva,","dejaré el resultado al Señor.","CORO:","Sembraré, sembraré,","mientras viva, simiente de amor.","Segaré, segaré,","al hallarme en la casa de Dios.","2. Sembraré en corazones sensibles","la doctrina del Dios de perdón.","Sembraré, sembraré mientras viva,","dejaré el resultado al Señor.","CORO:","Sembraré, sembraré,","mientras viva, simiente de amor.","Segaré, segaré,","al hallarme en la casa de Dios.","3. Sembraré en corazones de mármol","la bendita Palabra de Dios","Sembraré, sembraré mientras viva,","dejaré el resultado al Señor.","CORO:","Sembraré, sembraré,","mientras viva, simiente de amor.","Segaré, segaré,","al hallarme en la casa de Dios.","",""]];